name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
  - cron: '* * * * *'

jobs:
    bot:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Time Sync
        run:
          bash timesync.sh
      # - name: Create local changes
      #   run:
      #     bash test.sh
      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}