name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '* * * * *'


jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: |
          ...
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   bot:
#     runs-on: ubuntu-latest
#     steps:
#     # 首先copy git仓库到虚拟机上
#       - name: 'Checkout codes'
#       - uses: actions/checkout@v2
#         with:
#           persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
#           fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
#     # 执行仓库中的脚本文件
#       - name: 'UpdateTime'
#         run: 
#           bash test.sh

#       - name: Commit files
#         run:
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git commit -m "Add changes" -a

#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}

# name: Debugging with SSH
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v1
 
#      - name: Try Build
#        run: ./not-exist-file.sh it bloke build
 
#      - name: Start SSH via Ngrok
#        if: ${{ failure() }}
#        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
#        env:
#         # After sign up on the https://ngrok.com/
#         # You can find this token here: https://dashboard.ngrok.com/get-started/setup
#         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
 
#         # This password you will use when authorizing via SSH 
#         USER_PASS: ${{ secrets.USER_PASS }}
 
#      - name: Don't kill instace
#        if: ${{ failure() }}
#        run: sleep 1h # Prevent to killing instance after failure