name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '* * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
    # 执行仓库中的脚本文件
      - name: 'UpdateTime'
        run: 
          year=$(date +%Y)
          month=$(date +%m)
          day=$(date +%d)
          hour=$(date +%H)
          minu=$(date +%M)
          sed -i "15c\# \今天是公元$year年$month月$day日 $hour:$minu" README.md

          git config --global user.name "leoay"
          git config --global user.email "leoay23@hotmail.com"

          git add --all
          git commit -m "update date"
          git push origin main